# Generated by Django 5.2.8 on 2025-11-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DE_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc_code', models.CharField(max_length=12, null=False, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('uom', models.CharField(max_length=128, null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=512, null=True)),
                ('product_web_page', models.CharField(max_length=512, null=True)),
                ('image', models.CharField(max_length=512, null=True)),
                ('thumbnail_url', models.CharField(max_length=512, null=True)),
                ('thumbnail_width', models.CharField(max_length=512, null=True)),
                ('thumbnail_height', models.CharField(max_length=512, null=True)),
                ('usage', models.TextField(null=True)),
                ('ingredients', models.TextField(null=True)),
                ('nutrition', models.TextField(null=True)),
                ('categories', models.TextField(null=True)),
                ('manufacturer_name', models.CharField(max_length=255, null=True)),
                ('manufacturer_address', models.CharField(max_length=255, null=True)),
                ('manufacturer_address_2', models.CharField(max_length=255, null=True)),
                ('manufacturer_city', models.CharField(max_length=255, null=True)),
                ('manufacturer_state', models.CharField(max_length=255, null=True)),
                ('manufacturer_postal_code', models.CharField(max_length=255, null=True)),
                ('manufacturer_country', models.CharField(max_length=255, null=True)),
                ('manufacturer_phone', models.CharField(max_length=255, null=True)),
                ('manufacturer_contact', models.CharField(max_length=255, null=True)),
                ('gcp', models.CharField(max_length=255, null=True)),
                ('gcp_company', models.CharField(max_length=255, null=True)),
                ('gcp_gln', models.CharField(max_length=255, null=True)),
                ('gcp_address_1', models.CharField(max_length=255, null=True)),
                ('gcp_address_2', models.CharField(max_length=255, null=True)),
                ('gcp_city', models.CharField(max_length=255, null=True)),
                ('gcp_state', models.CharField(max_length=255, null=True)),
                ('gcp_postal_code', models.CharField(max_length=255, null=True)),
                ('gcp_country', models.CharField(max_length=255, null=True)),
                ('gcp_phone', models.CharField(max_length=255, null=True)),
                ('gcp_contact', models.CharField(max_length=255, null=True)),
                ('gcp_email', models.CharField(max_length=255, null=True)),
                ('gcp_fax', models.CharField(max_length=255, null=True)),
                ('prices', models.TextField(null=True)),
                ('system4', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Digit-Eyes Product',
                'verbose_name_plural': 'Digit-Eyes Products',
            },
        ),
    ]
