# Generated by Django 5.2.8 on 2025-11-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_delete_de_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='de_product_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
