# Generated by Django 5.2.8 on 2025-11-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_llmprompt_query_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="llmprompt",
            options={"ordering": ["query_type", "name"], "verbose_name": "LLM Prompt"},
        ),
        migrations.AlterModelOptions(
            name="llmqueryresult",
            options={"ordering": ["-created_at"], "verbose_name": "LLM Query Result"},
        ),
        migrations.AddField(
            model_name="llmprompt",
            name="response_schema",
            field=models.JSONField(
                blank=True,
                help_text="Expected JSON schema for the response (optional, for validation)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="llmprompt",
            name="schema_version",
            field=models.CharField(
                default="1.0", help_text="Version of the response schema", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="llmqueryresult",
            name="parse_attempts",
            field=models.IntegerField(
                default=1,
                help_text="Number of attempts needed to successfully parse the response",
            ),
        ),
        migrations.AddField(
            model_name="llmqueryresult",
            name="schema_version",
            field=models.CharField(
                default="1.0",
                help_text="Version of the schema used for this response",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="llmqueryresult",
            name="result",
            field=models.JSONField(
                help_text="The structured JSON response from the LLM"
            ),
        ),
    ]
