# Generated by Django 5.2.8 on 2025-11-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_update_for_structured_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmqueryresult',
            name='parse_strategy',
            field=models.CharField(blank=True, help_text="JSON parsing strategy that succeeded (e.g., 'direct', 'markdown_json', 'markdown_block', 'extract_braces')", max_length=50, null=True),
        ),
    ]
