"""
Django settings for product_finder project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    LOG_LEVEL=(str, None),
)

# Read .env file
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

# Allow requests from local network
# In DEBUG mode, use wildcard to allow all hosts for local network access
# In production, use the ALLOWED_HOSTS environment variable to specify allowed hosts
if DEBUG:
    # Allow all hosts in DEBUG mode for local network access
    # This enables requests from other devices/apps on your local network
    ALLOWED_HOSTS = ['*']
else:
    # In production, use environment variable or default to localhost
    default_hosts = ['localhost', '127.0.0.1']
    ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=default_hosts)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'graphene_django'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'product_finder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'product_finder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default='postgresql://postgres:postgres@localhost:6000/product_finder_dev')
}

# Test database override
DATABASES['default']['TEST'] = {
    'NAME': 'product_finder_test',
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging configuration
# https://docs.djangoproject.com/en/5.2/topics/logging/

# Determine log level from environment or default based on DEBUG mode
log_level = env('LOG_LEVEL', default='DEBUG' if DEBUG else 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # Optional: File handler for production
        # Uncomment and configure if you want file-based logging
        # 'file': {
        #     'class': 'logging.handlers.RotatingFileHandler',
        #     'filename': BASE_DIR / 'logs' / 'django.log',
        #     'maxBytes': 1024 * 1024 * 10,  # 10 MB
        #     'backupCount': 5,
        #     'formatter': 'verbose',
        # },
    },
    'root': {
        'handlers': ['console'],
        'level': log_level,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': log_level,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR' if not DEBUG else 'DEBUG',
            'propagate': False,
        },
        # Your application loggers
        'api': {
            'handlers': ['console'],
            'level': log_level,
            'propagate': False,
        },
        'api.services': {
            'handlers': ['console'],
            'level': log_level,
            'propagate': False,
        },
    },
}


# LLM Configuration
LLM_CONFIG = {
    'default_provider': env('DEFAULT_LLM_PROVIDER', default='perplexity'),
    'cache_ttl_days': env.int('LLM_CACHE_TTL_DAYS', default=30),
    'enable_caching': env.bool('LLM_ENABLE_CACHING', default=True),
    'providers': {
        'openai': {
            'api_key': env('OPENAI_API_KEY', default=''),
            'model': env('OPENAI_MODEL', default='gpt-4-turbo-preview'),
            'max_tokens': env.int('OPENAI_MAX_TOKENS', default=500),
            'temperature': env.float('OPENAI_TEMPERATURE', default=0.7),
        },
        'perplexity': {
            'api_key': env('PERPLEXITY_API_KEY', default=''),
            'model': env('PERPLEXITY_MODEL', default='llama-3.1-sonar-large-128k-online'),
            'max_tokens': env.int('PERPLEXITY_MAX_TOKENS', default=500),
            'temperature': env.float('PERPLEXITY_TEMPERATURE', default=0.7),
        }
    }
}
